[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://res.cloudinary.com https://*.graphassets.com https://*.hygraph.com https://*.google.com https://*.gstatic.com; script-src 'self' https://app.rybbit.io https://*.google.com https://*.gstatic.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[edge_functions]]
  function = "auth"
  path = "/nabmil/*"

[[headers]]
  for = "/nabmil/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"


# Strip common legacy extensions first (.php -> /page)
[[redirects]]
  from = "/:path.php"
  to = "/:path"
  status = 301
  force = true

# Canonical cleanup (slashes & trailing dashes)
[[redirects]]
  from = "/(.*)/$"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/(.*)-$"
  to = "/:splat"
  status = 301
  force = true


# Legacy Redirects - Limban Resort
[[redirects]]
  from = "/privacy"
  to = "/privacy-policy"
  status = 301

[[redirects]]
  from = "/adventures"
  to = "/activities"
  status = 301

[[redirects]]
  from = "/tc"
  to = "/guest-terms"
  status = 301

[[redirects]]
  from = "/explore"
  to = "/activities"
  status = 301

[[redirects]]
  from = "/facilities"
  to = "/about"
  status = 301

[[redirects]]
  from = "/am"
  to = "/dining"
  status = 301

[[redirects]]
  from = "/activities/about"
  to = "/activities"
  status = 301

[[redirects]]
  from = "/cabin"
  to = "/rooms/cabin"
  status = 301

[[redirects]]
  from = "/cottage"
  to = "/rooms/cottage"
  status = 301

[[redirects]]
  from = "/trip"
  to = "/safaris"
  status = 301

[[redirects]]
  from = "/dininglemayaabout"
  to = "/dining/lemaya"
  status = 301

[[redirects]]
  from = "/dining/lemaya/about"
  to = "/dining/lemaya"
  status = 301

[[redirects]]
  from = "/guest-galleryabout"
  to = "/guest-gallery"
  status = 301

[[redirects]]
  from = "/guest-gallery/about"
  to = "/guest-gallery"
  status = 301

[[redirects]]
  from = "/tadobaabout"
  to = "/tadoba"
  status = 301

[[redirects]]
  from = "/tadoba/about"
  to = "/tadoba"
  status = 301

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

[[redirects]]
  from = "/how-things-work"
  to = "/guest-terms"
  status = 301

[[redirects]]
  from = "/guest-policies"
  to = "/guest-terms"
  status = 301

[[redirects]]
  from = "/enquiry"
  to = "/contact"
  status = 301

[[redirects]]
  from = "/safari"
  to = "/safaris"
  status = 301

[[redirects]]
  from = "/enquire"
  to = "/contact"
  status = 301

[[redirects]]
  from = "/experience"
  to = "/activities"
  status = 301

[[redirects]]
  from = "/experiences"
  to = "/activities"
  status = 301

[[redirects]]
  from = "/stay"
  to = "/rooms"
  status = 301

[[redirects]]
  from = "/canvasvip"
  to = "/rooms/canvas"
  status = 301

[[redirects]]
  from = "/canvas"
  to = "/rooms/canvas"
  status = 301
